import type { Metadata } from "next";
import "../assets/styles/globals.scss";
import { Header } from "@/view";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <div className="h-screen !bg-red-400 w-screen">1</div>
      </body>
    </html>
  );
}
